# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 186553818774137ec449a249832766484b0e8db2b89b0dc23f0324afe58fdd06814b5c1d0751d4d014cf79cc585115e2bdebfc5ecb32a69c1795438cab1716ad

test:
  secret_key_base: 4b8beeec196b72257b0cf15bf5188a9c4966bc43abc7f5ad97ce82f1ffbd4fdd74ab2c416a8276f585b065cd260143f32a3686d3f2ab641d2694f10f0af6fd14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
